//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IronBoard.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IronBoard.Core.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IronBoard Error.
        /// </summary>
        internal static string Message_Title_Error {
            get {
                return ResourceManager.GetString("Message_Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to load error ({0}).
        /// </summary>
        internal static string MyTickets_LoadError {
            get {
                return ResourceManager.GetString("MyTickets_LoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading tickets.
        /// </summary>
        internal static string MyTickets_LoadingTickets {
            get {
                return ResourceManager.GetString("MyTickets_LoadingTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right-click a ticket to update with r{0}:{1}.
        /// </summary>
        internal static string MyTickets_TopHint {
            get {
                return ResourceManager.GetString("MyTickets_TopHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update #{0} with r{1}:{2}.
        /// </summary>
        internal static string MyTickets_UpdateTicketMenu {
            get {
                return ResourceManager.GetString("MyTickets_UpdateTicketMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updating ticket #{0}.
        /// </summary>
        internal static string MyTickets_UpdatingTicket {
            get {
                return ResourceManager.GetString("MyTickets_UpdatingTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to detecting repository.
        /// </summary>
        internal static string PostProgress_DetectRepository {
            get {
                return ResourceManager.GetString("PostProgress_DetectRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attaching source code.
        /// </summary>
        internal static string PostProgress_Diff {
            get {
                return ResourceManager.GetString("PostProgress_Diff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to creating main ticket.
        /// </summary>
        internal static string PostProgress_MainTicket {
            get {
                return ResourceManager.GetString("PostProgress_MainTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error generating diff: {0}.
        /// </summary>
        internal static string ReviewDetails_GenerateDiff_Error {
            get {
                return ResourceManager.GetString("ReviewDetails_GenerateDiff_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to generating subversion diff.
        /// </summary>
        internal static string ReviewDetails_GeneratingDiff {
            get {
                return ResourceManager.GetString("ReviewDetails_GeneratingDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New post-commit review ({0}).
        /// </summary>
        internal static string ReviewDetails_NewTicket {
            get {
                return ResourceManager.GetString("ReviewDetails_NewTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to i have done no testing and committed by mistake.
        /// </summary>
        internal static string ReviewDetails_NoTestingDone {
            get {
                return ResourceManager.GetString("ReviewDetails_NoTestingDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unit testing (see {0}).
        /// </summary>
        internal static string ReviewDetails_UnitTestingDone {
            get {
                return ResourceManager.GetString("ReviewDetails_UnitTestingDone", resourceCulture);
            }
        }
    }
}
