//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IronBoard.Daemon {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IronBoard.Daemon.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi,
        ///
        ///We have changed requirements on how to attach review links. Previous method by adding a web link didn&apos;t work because it&apos;s not indexable and not searchable. Could you please update the link using a method described here: https://mimecast.jira.com/wiki/display/NETDEV/Jira+Guidelines
        ///
        ///Thanks!.
        /// </summary>
        internal static string JiraBugger_AskToAddReviewLink {
            get {
                return ResourceManager.GetString("JiraBugger_AskToAddReviewLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello,
        ///
        ///Just wondering if there is any progress on this issue.
        ///
        ///Regards,
        ///Ivan..
        /// </summary>
        internal static string JiraBugger_Old_InProgress {
            get {
                return ResourceManager.GetString("JiraBugger_Old_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello,
        ///
        ///How is testing going on?
        ///
        ////Ivan.
        /// </summary>
        internal static string JiraBugger_Old_InTesting {
            get {
                return ResourceManager.GetString("JiraBugger_Old_InTesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://mimecast.jira.com/wiki/display/NETDEV/Jira+Guidelines.
        /// </summary>
        internal static string Link_JiraGuidelines {
            get {
                return ResourceManager.GetString("Link_JiraGuidelines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jira issue {0} does not exist, can we fix the link please? Thanks..
        /// </summary>
        internal static string ReviewBugger_InvalidJiraIssue {
            get {
                return ResourceManager.GetString("ReviewBugger_InvalidJiraIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi Guys,
        ///
        ///The issue wasn&apos;t upated for more than a day, can someone have a look at this?
        ///
        ///Thanks!.
        /// </summary>
        internal static string ReviewBugger_NotUpdated {
            get {
                return ResourceManager.GetString("ReviewBugger_NotUpdated", resourceCulture);
            }
        }
    }
}
